-- SAGE database bootstrap
--
-- Everything needed for a working instance, in the order it must run:
-- the schema, then the RPCs and indexes. Paste the whole file into the
-- Supabase SQL editor. Generated by scripts/build-bootstrap.sh — edit the
-- source files under prisma/, never this.

-- ═══ prisma/migrations/0001_init/migration.sql ═══
-- SAGE initial schema. Paste into Supabase SQL Editor and run.
CREATE EXTENSION IF NOT EXISTS vector;

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "vector";

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "avatarUrl" TEXT,
    "preferences" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Integration" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "scopes" TEXT[],
    "accessToken" TEXT NOT NULL,
    "refreshToken" TEXT,
    "expiresAt" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'active',

    CONSTRAINT "Integration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Thread" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "projectId" TEXT,
    "title" TEXT,
    "summary" TEXT,
    "pinned" BOOLEAN NOT NULL DEFAULT false,
    "archivedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Thread_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Message" (
    "id" TEXT NOT NULL,
    "threadId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" JSONB NOT NULL,
    "agentRunId" TEXT,
    "tokens" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Message_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Memory" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "embedding" vector(1536),
    "importance" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "confidence" DOUBLE PRECISION NOT NULL DEFAULT 0.8,
    "sourceType" TEXT NOT NULL,
    "sourceId" TEXT,
    "supersededBy" TEXT,
    "lastAccessedAt" TIMESTAMP(3),
    "accessCount" INTEGER NOT NULL DEFAULT 0,
    "expiresAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Memory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Source" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "projectId" TEXT,
    "kind" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "url" TEXT,
    "fileKey" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "error" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Source_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Chunk" (
    "id" TEXT NOT NULL,
    "sourceId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "embedding" vector(1536),
    "position" INTEGER NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "Chunk_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Project" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "emoji" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "context" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Note" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "projectId" TEXT,
    "kind" TEXT NOT NULL DEFAULT 'doc',
    "title" TEXT NOT NULL,
    "content" JSONB NOT NULL,
    "journalDate" TIMESTAMP(3),
    "aiGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Note_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Task" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "projectId" TEXT,
    "title" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'todo',
    "priority" INTEGER NOT NULL DEFAULT 2,
    "dueAt" TIMESTAMP(3),
    "source" TEXT NOT NULL DEFAULT 'user',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AgentRun" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "threadId" TEXT,
    "agent" TEXT NOT NULL,
    "goal" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'running',
    "plan" JSONB,
    "result" JSONB,
    "costUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt" TIMESTAMP(3),

    CONSTRAINT "AgentRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AgentStep" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "index" INTEGER NOT NULL,
    "kind" TEXT NOT NULL,
    "name" TEXT,
    "input" JSONB,
    "output" JSONB,
    "status" TEXT NOT NULL,
    "latencyMs" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AgentStep_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Automation" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "trigger" JSONB NOT NULL,
    "workflow" JSONB NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "lastRunAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Automation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AutomationRun" (
    "id" TEXT NOT NULL,
    "automationId" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "log" JSONB NOT NULL DEFAULT '[]',
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt" TIMESTAMP(3),

    CONSTRAINT "AutomationRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Reminder" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "remindAt" TIMESTAMP(3) NOT NULL,
    "recurring" TEXT,
    "channel" TEXT NOT NULL DEFAULT 'app',
    "status" TEXT NOT NULL DEFAULT 'pending',

    CONSTRAINT "Reminder_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Event" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Integration_userId_provider_key" ON "Integration"("userId", "provider");

-- CreateIndex
CREATE INDEX "Thread_userId_updatedAt_idx" ON "Thread"("userId", "updatedAt");

-- CreateIndex
CREATE INDEX "Message_threadId_createdAt_idx" ON "Message"("threadId", "createdAt");

-- CreateIndex
CREATE INDEX "Memory_userId_type_idx" ON "Memory"("userId", "type");

-- CreateIndex
CREATE INDEX "Source_userId_status_idx" ON "Source"("userId", "status");

-- CreateIndex
CREATE INDEX "Chunk_sourceId_position_idx" ON "Chunk"("sourceId", "position");

-- CreateIndex
CREATE INDEX "Note_userId_updatedAt_idx" ON "Note"("userId", "updatedAt");

-- CreateIndex
CREATE INDEX "Task_userId_status_dueAt_idx" ON "Task"("userId", "status", "dueAt");

-- CreateIndex
CREATE INDEX "AgentRun_userId_startedAt_idx" ON "AgentRun"("userId", "startedAt");

-- CreateIndex
CREATE INDEX "AgentStep_runId_index_idx" ON "AgentStep"("runId", "index");

-- CreateIndex
CREATE INDEX "Reminder_userId_remindAt_status_idx" ON "Reminder"("userId", "remindAt", "status");

-- CreateIndex
CREATE INDEX "Event_userId_type_createdAt_idx" ON "Event"("userId", "type", "createdAt");

-- AddForeignKey
ALTER TABLE "Integration" ADD CONSTRAINT "Integration_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Thread" ADD CONSTRAINT "Thread_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Thread" ADD CONSTRAINT "Thread_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Message" ADD CONSTRAINT "Message_threadId_fkey" FOREIGN KEY ("threadId") REFERENCES "Thread"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Memory" ADD CONSTRAINT "Memory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Source" ADD CONSTRAINT "Source_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Source" ADD CONSTRAINT "Source_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Chunk" ADD CONSTRAINT "Chunk_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "Source"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Project" ADD CONSTRAINT "Project_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Note" ADD CONSTRAINT "Note_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Note" ADD CONSTRAINT "Note_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgentRun" ADD CONSTRAINT "AgentRun_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgentStep" ADD CONSTRAINT "AgentStep_runId_fkey" FOREIGN KEY ("runId") REFERENCES "AgentRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Automation" ADD CONSTRAINT "Automation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AutomationRun" ADD CONSTRAINT "AutomationRun_automationId_fkey" FOREIGN KEY ("automationId") REFERENCES "Automation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Reminder" ADD CONSTRAINT "Reminder_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Event" ADD CONSTRAINT "Event_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- Vector ANN indexes (HNSW)
CREATE INDEX IF NOT EXISTS "Memory_embedding_idx" ON "Memory" USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS "Chunk_embedding_idx" ON "Chunk" USING hnsw (embedding vector_cosine_ops);

-- ═══ prisma/sql/0002_memory_rpcs.sql ═══
-- SAGE memory RPCs. Paste into Supabase SQL Editor and run.

-- Semantic memory recall (pgvector cosine ANN)
create or replace function match_memories(
  query_embedding vector(1536),
  match_count int default 12,
  p_user_id text default null
)
returns table(id text, type text, content text, importance double precision,
              confidence double precision, similarity double precision)
language sql stable as $$
  select m.id, m.type, m.content, m.importance, m.confidence,
         1 - (m.embedding <=> query_embedding) as similarity
  from "Memory" m
  where m.embedding is not null
    and m."supersededBy" is null
    -- A lapsed memory must not be recalled just because consolidation has not
    -- swept yet; expiry is checked at read time as well as at sweep time.
    and (m."expiresAt" is null or m."expiresAt" > now())
    and (p_user_id is null or m."userId" = p_user_id)
  order by m.embedding <=> query_embedding
  limit match_count;
$$;

-- Recall bookkeeping: bump access stats on used memories
create or replace function touch_memories(p_ids text[])
returns void language sql as $$
  update "Memory"
  set "accessCount" = "accessCount" + 1,
      "lastAccessedAt" = now()
  where id = any(p_ids);
$$;

-- ═══ prisma/sql/0003_knowledge_rpcs.sql ═══
-- SAGE knowledge search RPC. Paste into Supabase SQL Editor and run.

create or replace function match_chunks(
  query_embedding vector(1536),
  match_count int default 6,
  p_user_id text default null
)
returns table(id text, "sourceId" text, "sourceTitle" text, content text, similarity double precision)
language sql stable as $$
  select c.id, c."sourceId", s.title as "sourceTitle", c.content,
         1 - (c.embedding <=> query_embedding) as similarity
  from "Chunk" c
  join "Source" s on s.id = c."sourceId"
  where c.embedding is not null
    and s.status = 'ready'
    and (p_user_id is null or c."userId" = p_user_id)
  order by c.embedding <=> query_embedding
  limit match_count;
$$;

-- ═══ prisma/sql/0004_perf_indexes.sql ═══
-- Performance indexes.
--
-- Run once against the database (Supabase → SQL editor). CONCURRENTLY so it
-- never takes a write lock on a live table; that means each statement must be
-- run on its own, outside a transaction block.

-- AutomationRun had no index whatsoever. Every automations page load scans the
-- whole table, and the table grows by one row per automation per day forever,
-- so the page gets steadily slower with nothing to show for it. The order
-- matters: automationId narrows, startedAt DESC then satisfies "latest run"
-- without a sort.
CREATE INDEX CONCURRENTLY IF NOT EXISTS "AutomationRun_automationId_startedAt_idx"
  ON "AutomationRun" ("automationId", "startedAt" DESC);

-- Retention prunes by (userId, type, createdAt), which the existing composite
-- index already covers. The link graph does not: it filters on JSON paths
-- inside payload, which no btree can serve. These two expression indexes make
-- "everything linked to this thing" an index lookup rather than a scan of
-- every edge ever created.
CREATE INDEX CONCURRENTLY IF NOT EXISTS "Event_link_from_idx"
  ON "Event" ((payload -> 'from' ->> 'kind'), (payload -> 'from' ->> 'id'))
  WHERE type = 'link.edge';

CREATE INDEX CONCURRENTLY IF NOT EXISTS "Event_link_to_idx"
  ON "Event" ((payload -> 'to' ->> 'kind'), (payload -> 'to' ->> 'id'))
  WHERE type = 'link.edge';

-- Error grouping looks up one fingerprint on every captured error, and errors
-- arrive in bursts — exactly when the extra scan hurts most.
CREATE INDEX CONCURRENTLY IF NOT EXISTS "Event_error_fingerprint_idx"
  ON "Event" ((payload ->> 'fingerprint'))
  WHERE type = 'ops.error';

-- Deliberately NOT adding a Reminder index: (userId, remindAt, status) already
-- exists. A (userId, status, remindAt) variant would serve the cron sweep
-- slightly better, but a second index on a small, write-heavy table costs more
-- in write time and storage than it saves at this scale.

-- ═══ prisma/sql/0005_memory_vector_index.sql ═══
-- Make memory recall stop being the slowest thing in a reply.
-- Paste into the Supabase SQL Editor and run. Safe to re-run.
--
-- match_memories orders by `embedding <=> query_embedding` with no index on
-- that column, so every recall was a sequential scan computing a 1536-dimension
-- cosine distance for every memory on file. Measured at ~1.0-1.2s — and it sits
-- in front of the model call, so it was pure dead air before SAGE said anything
-- at all, on every single message. It also got worse with every memory stored,
-- which is the wrong direction for a system whose whole point is remembering
-- more over time.
--
-- HNSW rather than IVFFlat: it needs no training pass, does not degrade as rows
-- are added, and the memory table is far too small for IVFFlat's list tuning to
-- be worth reasoning about.

create index concurrently if not exists memory_embedding_hnsw
  on "Memory" using hnsw (embedding vector_cosine_ops)
  -- The partial predicate mirrors the RPC's own filters, so the index covers
  -- exactly the rows it searches. expiresAt is deliberately not in here: now()
  -- is not immutable and cannot appear in an index predicate. It stays a cheap
  -- filter on the handful of rows the index returns.
  where embedding is not null and "supersededBy" is null;

-- The other half of recall: touch_memories updates by id (already indexed), but
-- the non-vector fallback path orders by importance and createdAt per user.
create index concurrently if not exists memory_user_importance
  on "Memory" ("userId", importance desc, "createdAt" desc)
  where "supersededBy" is null;
