#!/usr/bin/env bash
# Regenerate prisma/bootstrap.sql — the one file a new instance pastes into the
# Supabase SQL editor. Run this after adding any migration or RPC, or setup
# instructions and reality will drift apart.
set -euo pipefail
cd "$(dirname "$0")/.."
{
  echo "-- SAGE database bootstrap"
  echo "--"
  echo "-- Everything needed for a working instance, in the order it must run:"
  echo "-- the schema, then the RPCs and indexes. Paste the whole file into the"
  echo "-- Supabase SQL editor. Generated by scripts/build-bootstrap.sh — edit the"
  echo "-- source files under prisma/, never this."
  echo
  echo "-- ═══ prisma/migrations/0001_init/migration.sql ═══"
  cat prisma/migrations/0001_init/migration.sql
  for f in prisma/sql/*.sql; do
    echo; echo "-- ═══ $f ═══"; cat "$f"
  done
} > prisma/bootstrap.sql
echo "wrote prisma/bootstrap.sql ($(wc -l < prisma/bootstrap.sql) lines)"
